Collections:
  - Name: MoCov2
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
        - MoCo
    Paper:
        URL: https://arxiv.org/abs/2003.04297
        Title: "Improved Baselines with Momentum Contrastive Learning"
    README: configs/selfsup/mocov2/README.md

Models:
  - Name: mocov2_resnet50_8xb32-coslr-200e_in1k
    In Collection: MoCo
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 67.58
    Config: configs/selfsup/mocov2/mocov2_resnet50_8xb32-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/moco/mocov2_resnet50_8xb32-coslr-200e_in1k_20220225-89e03af4.pth
