Collections:
  - Name: MAE
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - AdamW
      Training Resources: 8x A100-80G GPUs
      Architecture:
        - ViT
    Paper:
        URL: https://arxiv.org/abs/2111.06377
        Title: "Masked Autoencoders Are Scalable Vision Learners"
    README: configs/selfsup/mae/README.md

Models:
  - Name: mae_vit-base-p16_8xb512-amp-coslr-300e_in1k
    In Collection: MAE
    Metadata:
      Epochs: 300
      Batch Size: 4096
    Results: null
    Config: configs/selfsup/mae/mae_vit-base-p16_8xb512-amp-coslr-300e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/mae/mae_vit-base-p16_8xb512-fp16-coslr-300e_in1k/mae_vit-base-p16_8xb512-coslr-300e-fp16_in1k_20220829-c2cf66ba.pth
    Downstream:
      - Type: Image Classification
        Metadata:
          Epochs: 90
          Batch Size: 16384
        Results:
          - Task: Linear Evaluation
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 60.8
        Config: configs/benchmarks/classification/imagenet/vit-base-p16_linear-8xb2048-coslr-90e_in1k.py
      - Type: Image Classification
        Metadata:
          Epochs: 100
          Batch Size: 1024
        Results:
          - Task: Fine-tuning
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 83.1
        Config: configs/benchmarks/classification/imagenet/vit-base-p16_ft-8xb128-coslr-100e_in1k.py
