Collections:
  - Name: NPID
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
        - NPID
    Paper:
        URL: https://arxiv.org/abs/1805.01978
        Title: "Unsupervised Feature Learning via Non-Parametric Instance Discrimination"
    README: configs/selfsup/npid/README.md

Models:
  - Name: npid_resnet50_8xb32-steplr-200e_in1k
    In Collection: NPID
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results: null
    Config: configs/selfsup/npid/npid_resnet50_8xb32-steplr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/npid/npid_resnet50_8xb32-steplr-200e_in1k/npid_resnet50_8xb32-steplr-200e_in1k_20220825-a67c5440.pth
    Downstream:
      - Type: Image Classification
        Metadata:
          Epochs: 100
          Batch Size: 256
        Results:
          - Task: Linear Evaluation
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 58.3
        Config: configs/benchmarks/classification/imagenet/resnet50_linear-8xb32-steplr-100e_in1k.py
        Weights: https://download.openmmlab.com/mmselfsup/1.x/npid/npid_resnet50_8xb32-steplr-200e_in1k/resnet50_linear-8xb32-steplr-100e_in1k/resnet50_linear-8xb32-steplr-100e_in1k_20220825-661b736e.pth
