Collections:
  - Name: InterCLR
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
        - InterCLR
    Paper:
        URL: https://arxiv.org/abs/2008.11702
        Title: "Delving into Inter-Image Invariance for Unsupervised Visual Representations"
    README: configs/selfsup/interclr/README.md

Models:
  - Name: interclr-moco_resnet50_8xb32-coslr-200e_in1k
    In Collection: InterCLR
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 68.04
    Config: configs/selfsup/interclr/interclr-moco_resnet50_8xb32-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/interclr/interclr-moco_resnet50_8xb32-coslr-200e_in1k_20221206-38f8fdaf.pth
