# model settings
model = dict(
    type='MAE',
    backbone=dict(
        type='Vit',
        img_size=224,
        patch_size=16,
        in_chans=3,
        num_classes=0,
        embed_dim=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.0,
        init_values=0.0,
        use_learnable_pos_emb=False),
    neck=dict(
        type='MaeNeck',  # MAE decoder
        patch_size=16,
        num_patches=100,  # Need to be changed
        num_classes=768,
        embed_dim=384,
        depth=4,
        num_heads=6,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.0,
        init_values=0.0),
    head=dict(type='PixelHead'))
