Collections:
  - Name: SimSiam
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/2011.10566
        Title: "Exploring simple siamese representation learning"
    README: configs/selfsup/simsiam/README.md

Models:
  - Name: simsiam_resnet50_8xb32-coslr-100e_in1k
    In Collection: SimSiam
    Metadata:
      Epochs: 100
      Batch Size: 256
    Results: null
    Config: configs/selfsup/simsiam/simsiam_resnet50_8xb32-coslr-100e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/simsiam/simsiam_resnet50_8xb32-coslr-100e_in1k/simsiam_resnet50_8xb32-coslr-100e_in1k_20220825-d07cb2e6.pth
    Downstream:
      - Type: Image Classification
        Metadata:
          Epochs: 90
          Batch Size: 4096
        Results:
          - Task: Linear Evaluation
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 68.3
        Config: configs/benchmarks/classification/imagenet/resnet50_linear-8xb512-coslr-90e_in1k.py
        Weights: https://download.openmmlab.com/mmselfsup/1.x/simsiam/simsiam_resnet50_8xb32-coslr-100e_in1k/resnet50_linear-8xb512-coslr-90e_in1k/resnet50_linear-8xb512-coslr-90e_in1k_20220825-f53ba400.pth
  - Name: simsiam_resnet50_8xb32-coslr-200e_in1k
    In Collection: SimSiam
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results: null
    Config: configs/selfsup/simsiam/simsiam_resnet50_8xb32-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/simsiam/simsiam_resnet50_8xb32-coslr-200e_in1k/simsiam_resnet50_8xb32-coslr-200e_in1k_20220825-efe91299.pth
    Downstream:
      - Type: Image Classification
        Metadata:
          Epochs: 90
          Batch Size: 4096
        Results:
          - Task: Linear Evaluation
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 69.8
        Config: configs/benchmarks/classification/imagenet/resnet50_linear-8xb512-coslr-90e_in1k.py
        Weights: https://download.openmmlab.com/mmselfsup/1.x/simsiam/simsiam_resnet50_8xb32-coslr-200e_in1k/resnet50_linear-8xb512-coslr-90e_in1k/resnet50_linear-8xb512-coslr-90e_in1k_20220825-519b5135.pth
