Collections:
  - Name: SimSiam
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/2011.10566
        Title: "Exploring simple siamese representation learning"
    README: configs/selfsup/simsiam/README.md

Models:
  - Name: simsiam_resnet50_8xb32-coslr-100e_in1k
    In Collection: SimSiam
    Metadata:
      Epochs: 100
      Batch Size: 256
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 68.20
    Config: configs/selfsup/simsiam/simsiam_resnet50_8xb32-coslr-100e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/simsiam/simsiam_resnet50_8xb32-coslr-100e_in1k_20211230-65a0eff4.pth
  - Name: simsiam_resnet50_8xb32-coslr-200e_in1k
    In Collection: SimSiam
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 69.80
    Config: configs/selfsup/simsiam/simsiam_resnet50_8xb32-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/simsiam/simsiam_resnet50_8xb32-coslr-200e_in1k_20211213-b605f9f1.pth
