Collections:
  - Name: RotationPrediction
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/1803.07728
        Title: "Unsupervised representation learning by predicting image rotations"
    README: configs/selfsup/rotation_pred/README.md

Models:
  - Name: rotation-pred_resnet50_8xb16-steplr-70e_in1k
    In Collection: RotationPrediction
    Metadata:
      Epochs: 70
      Batch Size: 128
    Results: null
    Config: configs/selfsup/rotation_pred/rotation-pred_resnet50_8xb16-steplr-70e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/rotation_pred/rotation-pred_resnet50_8xb16-steplr-70e_in1k/rotation-pred_resnet50_8xb16-steplr-70e_in1k_20220825-a8bf5f69.pth
    Downstream:
      - Type: Image Classification
        Metadata:
          Epochs: 100
          Batch Size: 256
        Results:
          - Task: Linear Evaluation
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 47.0
        Config: configs/benchmarks/classification/imagenet/resnet50_linear-8xb32-steplr-100e_in1k.py
        Weights: https://download.openmmlab.com/mmselfsup/1.x/rotation_pred/rotation-pred_resnet50_8xb16-steplr-70e_in1k/resnet50_linear-8xb32-steplr-100e_in1k/resnet50_linear-8xb32-steplr-100e_in1k_20220825-7c6edcb3.pth
