Collections:
  - Name: DenseCL
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/2011.09157
        Title: "Dense contrastive learning for self-supervised visual pre-training"
    README: configs/selfsup/densecl/README.md

Models:
  - Name: densecl_resnet50_8xb32-coslr-200e_in1k
    In Collection: DenseCL
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 63.62
    Config: configs/selfsup/densecl/densecl_resnet50_8xb32-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/densecl/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth
