Collections:
  - Name: BarlowTwins
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - LARS
      Training Resources: 8x A100 GPUs
      Architecture:
        - ResNet
        - BarlowTwins
    Paper:
        URL: https://arxiv.org/abs/2103.03230
        Title: "Barlow Twins: Self-Supervised Learning via Redundancy Reduction"
    README: configs/selfsup/barlowtwins/README.md

Models:
  - Name: barlowtwins_resnet50_8xb256-coslr-300e_in1k
    In Collection: BarlowTwins
    Metadata:
      Epochs: 300
      Batch Size: 2048
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 71.66
    Config: configs/selfsup/barlowtwins/barlowtwins_resnet50_8xb256-coslr-300e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/barlowtwins/barlowtwins_resnet50_8xb256-coslr-300e_in1k_20220419-5ae15f89.pth
