Collections:
  - Name: RelativeLocation
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/1505.05192
        Title: "Unsupervised visual representation learning by context prediction"
    README: configs/selfsup/relative_loc/README.md

Models:
  - Name: relative-loc_resnet50_8xb64-steplr-70e_in1k
    In Collection: RelativeLocation
    Metadata:
      Epochs: 70
      Batch Size: 512
    Results: null
    Config: configs/selfsup/relative_loc/relative-loc_resnet50_8xb64-steplr-70e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/relative_loc/relative-loc_resnet50_8xb64-steplr-70e_in1k/relative-loc_resnet50_8xb64-steplr-70e_in1k_20220825-daae1b41.pth
    Downstream:
      - Type: Image Classification
        Metadata:
          Epochs: 100
          Batch Size: 256
        Results:
          - Task: Linear Evaluation
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 40.4
        Config: configs/benchmarks/classification/imagenet/resnet50_linear-8xb32-steplr-100e_in1k.py
        Weights: https://download.openmmlab.com/mmselfsup/1.x/relative_loc/relative-loc_resnet50_8xb64-steplr-70e_in1k/resnet50_linear-8xb32-steplr-100e_in1k/resnet50_linear-8xb32-steplr-100e_in1k_20220825-c2a0b188.pth
