Collections:
  - Name: BEiT
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - AdamW
      Training Resources: 8x A100-80G GPUs
      Architecture:
        - ViT
    Paper:
        URL: https://arxiv.org/abs/2106.08254
        Title: "BEiT: BERT Pre-Training of Image Transformers"
    README: configs/selfsup/beit/README.md

Models:
  - Name: beit_vit-base-p16_8xb256-amp-coslr-300e_in1k
    In Collection: BEiT
    Metadata:
      Epochs: 300
      Batch Size: 2048
    Results: null
    Config: configs/selfsup/beit/beit_vit-base-p16_8xb256-amp-coslr-300e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/beit/beit_vit-base-p16_8xb256-amp-coslr-300e_in1k/beit_vit-base-p16_8xb256-amp-coslr-300e_in1k_20221128-ab79e626.pth
    Downstream:
      - Type: Image Classification
        Metadata:
          Epochs: 100
          Batch Size: 1024
        Results:
          - Task: Fine-tuning
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 83.1
        Config: configs/selfsup/beit/classification/vit-base-p16_ft-8xb128-coslr-100e_in1k.py
        Weights: https://download.openmmlab.com/mmselfsup/1.x/beit/beit_vit-base-p16_8xb256-amp-coslr-300e_in1k/vit-base-p16_ft-8xb128-coslr-100e_in1k/vit-base-p16_ft-8xb128-coslr-100e_in1k_20221128-0ca393e9.pth
