Collections:
  - Name: SimCLR
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - LARS
      Training Resources: 8x V100 GPUs (b256), 16x A100-80G GPUs (b4096)
      Architecture:
        - ResNet
        - SimCLR
    Paper:
        URL: https://arxiv.org/abs/2002.05709
        Title: "A simple framework for contrastive learning of visual representations"
    README: configs/selfsup/simclr/README.md

Models:
  - Name: simclr_resnet50_8xb32-coslr-200e_in1k
    In Collection: SimCLR
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 62.56
    Config: configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/simclr/simclr_resnet50_8xb32-coslr-200e_in1k_20220428-46ef6bb9.pth
  - Name: simclr_resnet50_16xb256-coslr-200e_in1k
    In Collection: SimCLR
    Metadata:
      Epochs: 200
      Batch Size: 4096
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 66.66
    Config: configs/selfsup/simclr/simclr_resnet50_16xb256-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/simclr/simclr_resnet50_16xb256-coslr-200e_in1k_20220428-8c24b063.pth
