Collections:
  - Name: SimCLR
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - LARS
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
        - SimCLR
    Paper:
        URL: https://arxiv.org/abs/2002.05709
        Title: "A simple framework for contrastive learning of visual representations"
    README: configs/selfsup/simclr/README.md

Models:
  - Name: simclr_resnet50_8xb32-coslr-200e_in1k
    In Collection: SimCLR
    Metadata:
      Epochs: 200
      Batch Size: 256
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 57.28
    Config: configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/simclr/simclr_resnet50_8xb32-coslr-200e_in1k_20220225-97d2abef.pth
