Collections:
  - Name: DeepCluster
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
        - DeepCluster
    Paper:
        URL: https://arxiv.org/abs/1807.05520
        Title: "Deep clustering for unsupervised learning of visual features"
    README: configs/selfsup/deepcluster/README.md

Models:
  - Name: deepcluster-sobel_resnet50_8xb64-steplr-200e_in1k
    In Collection: DeepCluster
    Metadata:
      Epochs: 200
      Batch Size: 512
    Results:
      - Task: Self-Supervised Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 46.92
    Config: configs/selfsup/deepcluster/deepcluster-sobel_resnet50_8xb64-steplr-200e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/deepcluster/deepcluster-sobel_resnet50_8xb64-steplr-200e_in1k-bb8681e2.pth
