name: merge_stage_test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'README_zh-CN.md'
      - 'docs/**'
      - 'demo/**'
      - '.dev_scripts/**'
      - '.circleci/**'
      - 'projects/**'
    branches:
      - dev-1.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_cpu_py:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        torch: [1.8.1]
        include:
          - torch: 1.8.1
            torchvision: 0.9.1
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install pip --upgrade
      - name: Install PyTorch
        run: pip install torch==${{matrix.torch}}+cpu torchvision==${{matrix.torchvision}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install MMSelfSup dependencies
        run: |
          pip install -U openmim
          mim install mmengine
          mim install 'mmcv>=2.0.0'
          mim install 'mmdet>=3.0.0rc0'
          mim install 'mmsegmentation>=1.0.0rc0'
          pip install -r requirements/tests.txt
      - name: Build and install
        run: rm -rf .eggs && pip install -e .
      - name: Run unittests and generate coverage report
        run: |
          coverage run --branch --source mmselfsup -m pytest tests/
          coverage xml
          coverage report -m

  build_cpu_pt:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8]
        torch: [1.8.1, 1.9.1, 1.10.1, 1.11.0, 1.12.1]
        include:
          - torch: 1.8.1
            torchvision: 0.9.1
          - torch: 1.9.1
            torchvision: 0.10.1
          - torch: 1.10.1
            torchvision: 0.11.2
          - torch: 1.11.0
            torchvision: 0.12.0
          - torch: 1.12.1
            torchvision: 0.13.1
          - torch: 2.0.0
            torchvision: 0.15.1
            python-version: 3.8
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PyTorch
        run: pip install torch==${{matrix.torch}}+cpu torchvision==${{matrix.torchvision}}+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      - name: Install MMSelfSup dependencies
        run: |
          pip install -U openmim
          mim install mmengine
          mim install 'mmcv>=2.0.0'
          mim install 'mmdet>=3.0.0rc0'
          mim install 'mmsegmentation>=1.0.0rc0'
          pip install -r requirements/tests.txt
      - name: Build and install
        run: rm -rf .eggs && pip install -e .
      - name: Run unittests and generate coverage report
        run: |
          coverage run --branch --source mmselfsup -m pytest tests/
          coverage xml
          coverage report -m
      # Only upload coverage report for python3.8 && pytorch1.9.1
      - name: Upload coverage to Codecov
        if: ${{matrix.torch == '1.9.1' && matrix.python-version == '3.8'}}
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false

  build_cu102:
    runs-on: ubuntu-22.04
    container:
      image: pytorch/pytorch:1.8.1-cuda10.2-cudnn7-devel
    strategy:
      matrix:
        python-version: [3.7]
        include:
          - torch: 1.8.1
            cuda: 10.2
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install pip --upgrade
      - name: Fetch GPG keys
        run: |
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
      - name: Install Python-dev
        run: apt-get update && apt-get install -y python${{matrix.python-version}}-dev
        if: ${{matrix.python-version != 3.9}}
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6
      - name: Install MMSelfSup dependencies
        run: |
          pip install -U openmim
          mim install mmengine
          mim install 'mmcv>=2.0.0'
          mim install 'mmdet>=3.0.0rc0'
          mim install 'mmsegmentation>=1.0.0rc0'
          pip install -r requirements/tests.txt
      - name: Build and install
        run: |
          pip install -e .

  build_windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        python: [3.7]
        platform: [cpu, cu111]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python.exe -m pip install --upgrade pip
      - name: Install lmdb
        run: pip install lmdb
      - name: Install PyTorch
        run: pip install torch==1.8.1+${{matrix.platform}} torchvision==0.9.1+${{matrix.platform}} -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
      - name: Install MMSelfSup dependencies
        run: |
          pip install -U openmim
          mim install mmengine
          mim install 'mmcv>=2.0.0'
          mim install 'mmdet>=3.0.0rc0'
          mim install 'mmsegmentation>=1.0.0rc0'
          pip install -r requirements/tests.txt
      - name: Build and install
        run: |
          pip install -e .
      - name: Run unittests and generate coverage report
        run: |
          pytest tests/
