Collections:
  - Name: EVA
    Metadata:
      Training Data: ImageNet-1k
      Training Techniques:
        - AdamW
      Training Resources: 16x A100-80G GPUs
      Architecture:
        - ViT
    Paper:
        URL: https://arxiv.org/abs/2211.07636
        Title: "EVA: Exploring the Limits of Masked Visual Representation Learning at Scale"
    README: configs/selfsup/eva/README.md

Models:
  - Name: eva-mae-style_vit-base-p16_16xb256-coslr-400e_in1k
    In Collection: EVA
    Metadata:
      Epochs: 400
      Batch Size: 4096
    Results: null
    Config: configs/selfsup/eva/eva-mae-style_vit-base-p16_16xb256-coslr-400e_in1k.py
    Weights: https://download.openmmlab.com/mmselfsup/1.x/eva/eva-mae-style_vit-base-p16_16xb256-coslr-400e_in1k/eva-mae-style_vit-base-p16_16xb256-coslr-400e_in1k_20221226-26d90f07.pth
    Downstream:
      - Type: Image Classification
        Metadata:
          Epochs: 100
          Batch Size: 1024
        Results:
          - Task: Fine-tuning
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 83.7
        Config: configs/selfsup/eva/classification/vit-base-p16_ft-8xb128-coslr-100e_in1k.py
        Weights: https://download.openmmlab.com/mmselfsup/1.x/eva/eva-mae-style_vit-base-p16_16xb256-coslr-400e_in1k/vit-base-p16_ft-8xb128-coslr-100e_in1k/vit-base-p16_ft-8xb128-coslr-100e_in1k_20221226-f61cf992.pth
      - Type: Image Classification
        Metadata:
          Epochs: 100
          Batch Size: 16384
        Results:
          - Task: Linear Evaluation
            Dataset: ImageNet-1k
            Metrics:
              Top 1 Accuracy: 69.0
        Config: configs/selfsup/eva/classification/vit-base-p16_linear-8xb2048-coslr-100e_in1k.py
        Weights: https://download.openmmlab.com/mmselfsup/1.x/eva/eva-mae-style_vit-base-p16_16xb256-coslr-400e_in1k/vit-base-p16_linear-8xb2048-coslr-100e_in1k/vit-base-p16_linear-8xb2048-coslr-100e_in1k_20221226-ef51bf09.pth
